//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// #DA Schema Name:"PC"
// #DA Schema Source:"AttendanceSystemClientV2.relativityClient"
// #DA Skipped Tables:"BJTABLE_09_VIEW,DMTABLE_08_BS,DMTABLE_08_VIEW,DSS_E1_BAS009,DSS_E1_SYS01,DSS_E1_SYS100,DSS_E1_SYS101,DSS_E1_SYS102,DSS_E1_SYS103,DSS_E1_SYS104,DSS_E1_SYS105,DSS_E1_SYS106,DSS_E1_SYS107,DSS_E1_TMP100,KCTABLE_04,KKTABLE_05_VIEW,RLSBGROUP_10,RLSBGROUPSTUDENT_11,SKTABLE_07_VIEW,XKTABLE_06_BS,XKTABLE_06_VIEW,XSTABLE_01_BS,XSTABLE_01_VIEW,XYTABLE_02"
namespace AttendanceSystemClientV2.PC {
    
    [RemObjects.DataAbstract.Linq.TableName("BJTABLE_09_VIEWRO")]
    public partial class BJTABLE_09_VIEWRO : System.ICloneable, System.ComponentModel.INotifyPropertyChanged, System.ComponentModel.INotifyPropertyChanging {
        protected BJTABLE_09_VIEWRO m____OldValues;
        private decimal f____BJID;
        private string f____BJNAME;
        private decimal f____XYID;
        private string f____XYNAME;
        [RemObjects.DataAbstract.Linq.FieldName("BJID")]
        [RemObjects.DataAbstract.Linq.DataType(RemObjects.DataAbstract.Schema.DataType.Decimal)]
        [RemObjects.DataAbstract.Linq.PrimaryKey()]
        [RemObjects.DataAbstract.Linq.LogChanges()]
        public virtual decimal BJID {
            get {
                return f____BJID;
            }
            set {
                if ((System.Collections.Generic.Comparer<decimal>.Default.Compare(this.f____BJID, value) != 0)) {
                    this.OnPropertyChanging("BJID");
                    f____BJID = value;
                    this.OnPropertyChanged("BJID");
                }
            }
        }
        [RemObjects.DataAbstract.Linq.FieldName("BJNAME")]
        [RemObjects.DataAbstract.Linq.DataType(RemObjects.DataAbstract.Schema.DataType.WideString)]
        [RemObjects.DataAbstract.Linq.LogChanges()]
        public virtual string BJNAME {
            get {
                return f____BJNAME;
            }
            set {
                if ((System.Collections.Generic.Comparer<string>.Default.Compare(this.f____BJNAME, value) != 0)) {
                    this.OnPropertyChanging("BJNAME");
                    f____BJNAME = value;
                    this.OnPropertyChanged("BJNAME");
                }
            }
        }
        [RemObjects.DataAbstract.Linq.FieldName("XYID")]
        [RemObjects.DataAbstract.Linq.DataType(RemObjects.DataAbstract.Schema.DataType.Decimal)]
        [RemObjects.DataAbstract.Linq.LogChanges()]
        public virtual decimal XYID {
            get {
                return f____XYID;
            }
            set {
                if ((System.Collections.Generic.Comparer<decimal>.Default.Compare(this.f____XYID, value) != 0)) {
                    this.OnPropertyChanging("XYID");
                    f____XYID = value;
                    this.OnPropertyChanged("XYID");
                }
            }
        }
        [RemObjects.DataAbstract.Linq.FieldName("XYNAME")]
        [RemObjects.DataAbstract.Linq.DataType(RemObjects.DataAbstract.Schema.DataType.WideString)]
        [RemObjects.DataAbstract.Linq.LogChanges()]
        public virtual string XYNAME {
            get {
                return f____XYNAME;
            }
            set {
                f____XYNAME = value;
            }
        }
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
        object System.ICloneable.Clone() {
            BJTABLE_09_VIEWRO v____new = new BJTABLE_09_VIEWRO();
            v____new.f____BJID = this.f____BJID;
            v____new.f____BJNAME = this.f____BJNAME;
            v____new.f____XYID = this.f____XYID;
            v____new.f____XYNAME = this.f____XYNAME;
            return v____new;
        }
        public virtual void BeginUpdate() {
            this.m____OldValues = ((BJTABLE_09_VIEWRO)(((System.ICloneable)(this)).Clone()));
        }
        public virtual void EndUpdate(RemObjects.DataAbstract.Linq.LinqDataAdapter dataAdapter) {
            dataAdapter.UpdateRow<BJTABLE_09_VIEWRO>(this.m____OldValues, this);
            this.m____OldValues = null;
        }
        public virtual void CancelUpdate() {
            this.m____OldValues = null;
        }
        protected virtual void OnPropertyChanging(string parameterName) {
            if ((this.PropertyChanging != null)) {
                this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(parameterName));
            }
        }
        protected virtual void OnPropertyChanged(string parameterName) {
            if (((this.PropertyChanged != null) 
                        && (this.m____OldValues == null))) {
                this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(parameterName));
            }
        }
    }
    [RemObjects.DataAbstract.Linq.TableName("DMTABLE_08_NOPIC_VIEW")]
    public partial class DMTABLE_08_NOPIC_VIEW : System.ICloneable, System.ComponentModel.INotifyPropertyChanged, System.ComponentModel.INotifyPropertyChanging {
        protected DMTABLE_08_NOPIC_VIEW m____OldValues;
        private long f____DMNO;
        private System.Nullable<long> f____SKNO;
        private System.Nullable<long> f____KKNO;
        private string f____KKNAME;
        private string f____XSID;
        private string f____XSNAME;
        private System.Nullable<short> f____DKZT;
        private System.Nullable<System.DateTime> f____DMSJ1;
        private System.Nullable<System.DateTime> f____DMSJ2;
        private System.Nullable<System.DateTime> f____DMSJ3;
        private System.Nullable<System.DateTime> f____POSTDATE;
        private System.Nullable<decimal> f____POSTMANNO;
        [RemObjects.DataAbstract.Linq.FieldName("DMNO")]
        [RemObjects.DataAbstract.Linq.DataType(RemObjects.DataAbstract.Schema.DataType.LargeInt)]
        [RemObjects.DataAbstract.Linq.PrimaryKey()]
        [RemObjects.DataAbstract.Linq.LogChanges()]
        public virtual long DMNO {
            get {
                return f____DMNO;
            }
            set {
                if ((System.Collections.Generic.Comparer<long>.Default.Compare(this.f____DMNO, value) != 0)) {
                    this.OnPropertyChanging("DMNO");
                    f____DMNO = value;
                    this.OnPropertyChanged("DMNO");
                }
            }
        }
        [RemObjects.DataAbstract.Linq.FieldName("SKNO")]
        [RemObjects.DataAbstract.Linq.DataType(RemObjects.DataAbstract.Schema.DataType.LargeInt)]
        [RemObjects.DataAbstract.Linq.LogChanges()]
        public virtual System.Nullable<long> SKNO {
            get {
                return f____SKNO;
            }
            set {
                if ((System.Collections.Generic.Comparer<System.Nullable<long>>.Default.Compare(this.f____SKNO, value) != 0)) {
                    this.OnPropertyChanging("SKNO");
                    f____SKNO = value;
                    this.OnPropertyChanged("SKNO");
                }
            }
        }
        [RemObjects.DataAbstract.Linq.FieldName("KKNO")]
        [RemObjects.DataAbstract.Linq.DataType(RemObjects.DataAbstract.Schema.DataType.LargeInt)]
        [RemObjects.DataAbstract.Linq.LogChanges()]
        public virtual System.Nullable<long> KKNO {
            get {
                return f____KKNO;
            }
            set {
                f____KKNO = value;
            }
        }
        [RemObjects.DataAbstract.Linq.FieldName("KKNAME")]
        [RemObjects.DataAbstract.Linq.DataType(RemObjects.DataAbstract.Schema.DataType.WideString)]
        [RemObjects.DataAbstract.Linq.LogChanges()]
        public virtual string KKNAME {
            get {
                return f____KKNAME;
            }
            set {
                f____KKNAME = value;
            }
        }
        [RemObjects.DataAbstract.Linq.FieldName("XSID")]
        [RemObjects.DataAbstract.Linq.DataType(RemObjects.DataAbstract.Schema.DataType.WideString)]
        [RemObjects.DataAbstract.Linq.LogChanges()]
        public virtual string XSID {
            get {
                return f____XSID;
            }
            set {
                if ((System.Collections.Generic.Comparer<string>.Default.Compare(this.f____XSID, value) != 0)) {
                    this.OnPropertyChanging("XSID");
                    f____XSID = value;
                    this.OnPropertyChanged("XSID");
                }
            }
        }
        [RemObjects.DataAbstract.Linq.FieldName("XSNAME")]
        [RemObjects.DataAbstract.Linq.DataType(RemObjects.DataAbstract.Schema.DataType.WideString)]
        [RemObjects.DataAbstract.Linq.LogChanges()]
        public virtual string XSNAME {
            get {
                return f____XSNAME;
            }
            set {
                f____XSNAME = value;
            }
        }
        [RemObjects.DataAbstract.Linq.FieldName("DKZT")]
        [RemObjects.DataAbstract.Linq.DataType(RemObjects.DataAbstract.Schema.DataType.SmallInt)]
        [RemObjects.DataAbstract.Linq.LogChanges()]
        public virtual System.Nullable<short> DKZT {
            get {
                return f____DKZT;
            }
            set {
                if ((System.Collections.Generic.Comparer<System.Nullable<short>>.Default.Compare(this.f____DKZT, value) != 0)) {
                    this.OnPropertyChanging("DKZT");
                    f____DKZT = value;
                    this.OnPropertyChanged("DKZT");
                }
            }
        }
        [RemObjects.DataAbstract.Linq.FieldName("DMSJ1")]
        [RemObjects.DataAbstract.Linq.DataType(RemObjects.DataAbstract.Schema.DataType.DateTime)]
        [RemObjects.DataAbstract.Linq.LogChanges()]
        public virtual System.Nullable<System.DateTime> DMSJ1 {
            get {
                return f____DMSJ1;
            }
            set {
                if ((System.Collections.Generic.Comparer<System.Nullable<System.DateTime>>.Default.Compare(this.f____DMSJ1, value) != 0)) {
                    this.OnPropertyChanging("DMSJ1");
                    f____DMSJ1 = value;
                    this.OnPropertyChanged("DMSJ1");
                }
            }
        }
        [RemObjects.DataAbstract.Linq.FieldName("DMSJ2")]
        [RemObjects.DataAbstract.Linq.DataType(RemObjects.DataAbstract.Schema.DataType.DateTime)]
        [RemObjects.DataAbstract.Linq.LogChanges()]
        public virtual System.Nullable<System.DateTime> DMSJ2 {
            get {
                return f____DMSJ2;
            }
            set {
                if ((System.Collections.Generic.Comparer<System.Nullable<System.DateTime>>.Default.Compare(this.f____DMSJ2, value) != 0)) {
                    this.OnPropertyChanging("DMSJ2");
                    f____DMSJ2 = value;
                    this.OnPropertyChanged("DMSJ2");
                }
            }
        }
        [RemObjects.DataAbstract.Linq.FieldName("DMSJ3")]
        [RemObjects.DataAbstract.Linq.DataType(RemObjects.DataAbstract.Schema.DataType.DateTime)]
        [RemObjects.DataAbstract.Linq.LogChanges()]
        public virtual System.Nullable<System.DateTime> DMSJ3 {
            get {
                return f____DMSJ3;
            }
            set {
                if ((System.Collections.Generic.Comparer<System.Nullable<System.DateTime>>.Default.Compare(this.f____DMSJ3, value) != 0)) {
                    this.OnPropertyChanging("DMSJ3");
                    f____DMSJ3 = value;
                    this.OnPropertyChanged("DMSJ3");
                }
            }
        }
        [RemObjects.DataAbstract.Linq.FieldName("POSTDATE")]
        [RemObjects.DataAbstract.Linq.DataType(RemObjects.DataAbstract.Schema.DataType.DateTime)]
        [RemObjects.DataAbstract.Linq.LogChanges()]
        public virtual System.Nullable<System.DateTime> POSTDATE {
            get {
                return f____POSTDATE;
            }
            set {
                if ((System.Collections.Generic.Comparer<System.Nullable<System.DateTime>>.Default.Compare(this.f____POSTDATE, value) != 0)) {
                    this.OnPropertyChanging("POSTDATE");
                    f____POSTDATE = value;
                    this.OnPropertyChanged("POSTDATE");
                }
            }
        }
        [RemObjects.DataAbstract.Linq.FieldName("POSTMANNO")]
        [RemObjects.DataAbstract.Linq.DataType(RemObjects.DataAbstract.Schema.DataType.Decimal)]
        [RemObjects.DataAbstract.Linq.LogChanges()]
        public virtual System.Nullable<decimal> POSTMANNO {
            get {
                return f____POSTMANNO;
            }
            set {
                if ((System.Collections.Generic.Comparer<System.Nullable<decimal>>.Default.Compare(this.f____POSTMANNO, value) != 0)) {
                    this.OnPropertyChanging("POSTMANNO");
                    f____POSTMANNO = value;
                    this.OnPropertyChanged("POSTMANNO");
                }
            }
        }
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
        object System.ICloneable.Clone() {
            DMTABLE_08_NOPIC_VIEW v____new = new DMTABLE_08_NOPIC_VIEW();
            v____new.f____DMNO = this.f____DMNO;
            v____new.f____SKNO = this.f____SKNO;
            v____new.f____KKNO = this.f____KKNO;
            v____new.f____KKNAME = this.f____KKNAME;
            v____new.f____XSID = this.f____XSID;
            v____new.f____XSNAME = this.f____XSNAME;
            v____new.f____DKZT = this.f____DKZT;
            v____new.f____DMSJ1 = this.f____DMSJ1;
            v____new.f____DMSJ2 = this.f____DMSJ2;
            v____new.f____DMSJ3 = this.f____DMSJ3;
            v____new.f____POSTDATE = this.f____POSTDATE;
            v____new.f____POSTMANNO = this.f____POSTMANNO;
            return v____new;
        }
        public virtual void BeginUpdate() {
            this.m____OldValues = ((DMTABLE_08_NOPIC_VIEW)(((System.ICloneable)(this)).Clone()));
        }
        public virtual void EndUpdate(RemObjects.DataAbstract.Linq.LinqDataAdapter dataAdapter) {
            dataAdapter.UpdateRow<DMTABLE_08_NOPIC_VIEW>(this.m____OldValues, this);
            this.m____OldValues = null;
        }
        public virtual void CancelUpdate() {
            this.m____OldValues = null;
        }
        protected virtual void OnPropertyChanging(string parameterName) {
            if ((this.PropertyChanging != null)) {
                this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(parameterName));
            }
        }
        protected virtual void OnPropertyChanged(string parameterName) {
            if (((this.PropertyChanged != null) 
                        && (this.m____OldValues == null))) {
                this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(parameterName));
            }
        }
    }
    [RemObjects.DataAbstract.Linq.TableName("JSANDKKVIEWRO")]
    public partial class JSANDKKVIEWRO : System.ICloneable, System.ComponentModel.INotifyPropertyChanged, System.ComponentModel.INotifyPropertyChanging {
        protected JSANDKKVIEWRO m____OldValues;
        private long f____JSID;
        private string f____JSNAME;
        private string f____JSSEX;
        private System.Nullable<long> f____XYID;
        private System.Nullable<System.DateTime> f____JKDATE;
        private System.Nullable<long> f____KCID;
        private System.Nullable<System.DateTime> f____KKDATE;
        private string f____KKNAME;
        private long f____KKNO;
        private System.Nullable<System.DateTime> f____KSDATE;
        private System.Nullable<decimal> f____RLSBNO;
        private System.Nullable<long> f____XXRS;
        [RemObjects.DataAbstract.Linq.FieldName("JSID")]
        [RemObjects.DataAbstract.Linq.DataType(RemObjects.DataAbstract.Schema.DataType.LargeInt)]
        [RemObjects.DataAbstract.Linq.LogChanges()]
        public virtual long JSID {
            get {
                return f____JSID;
            }
            set {
                if ((System.Collections.Generic.Comparer<long>.Default.Compare(this.f____JSID, value) != 0)) {
                    this.OnPropertyChanging("JSID");
                    f____JSID = value;
                    this.OnPropertyChanged("JSID");
                }
            }
        }
        [RemObjects.DataAbstract.Linq.FieldName("JSNAME")]
        [RemObjects.DataAbstract.Linq.DataType(RemObjects.DataAbstract.Schema.DataType.WideString)]
        [RemObjects.DataAbstract.Linq.LogChanges()]
        public virtual string JSNAME {
            get {
                return f____JSNAME;
            }
            set {
                if ((System.Collections.Generic.Comparer<string>.Default.Compare(this.f____JSNAME, value) != 0)) {
                    this.OnPropertyChanging("JSNAME");
                    f____JSNAME = value;
                    this.OnPropertyChanged("JSNAME");
                }
            }
        }
        [RemObjects.DataAbstract.Linq.FieldName("JSSEX")]
        [RemObjects.DataAbstract.Linq.DataType(RemObjects.DataAbstract.Schema.DataType.WideString)]
        [RemObjects.DataAbstract.Linq.LogChanges()]
        public virtual string JSSEX {
            get {
                return f____JSSEX;
            }
            set {
                if ((System.Collections.Generic.Comparer<string>.Default.Compare(this.f____JSSEX, value) != 0)) {
                    this.OnPropertyChanging("JSSEX");
                    f____JSSEX = value;
                    this.OnPropertyChanged("JSSEX");
                }
            }
        }
        [RemObjects.DataAbstract.Linq.FieldName("XYID")]
        [RemObjects.DataAbstract.Linq.DataType(RemObjects.DataAbstract.Schema.DataType.LargeInt)]
        [RemObjects.DataAbstract.Linq.LogChanges()]
        public virtual System.Nullable<long> XYID {
            get {
                return f____XYID;
            }
            set {
                if ((System.Collections.Generic.Comparer<System.Nullable<long>>.Default.Compare(this.f____XYID, value) != 0)) {
                    this.OnPropertyChanging("XYID");
                    f____XYID = value;
                    this.OnPropertyChanged("XYID");
                }
            }
        }
        [RemObjects.DataAbstract.Linq.FieldName("JKDATE")]
        [RemObjects.DataAbstract.Linq.DataType(RemObjects.DataAbstract.Schema.DataType.DateTime)]
        [RemObjects.DataAbstract.Linq.LogChanges()]
        public virtual System.Nullable<System.DateTime> JKDATE {
            get {
                return f____JKDATE;
            }
            set {
                if ((System.Collections.Generic.Comparer<System.Nullable<System.DateTime>>.Default.Compare(this.f____JKDATE, value) != 0)) {
                    this.OnPropertyChanging("JKDATE");
                    f____JKDATE = value;
                    this.OnPropertyChanged("JKDATE");
                }
            }
        }
        [RemObjects.DataAbstract.Linq.FieldName("KCID")]
        [RemObjects.DataAbstract.Linq.DataType(RemObjects.DataAbstract.Schema.DataType.LargeInt)]
        [RemObjects.DataAbstract.Linq.LogChanges()]
        public virtual System.Nullable<long> KCID {
            get {
                return f____KCID;
            }
            set {
                if ((System.Collections.Generic.Comparer<System.Nullable<long>>.Default.Compare(this.f____KCID, value) != 0)) {
                    this.OnPropertyChanging("KCID");
                    f____KCID = value;
                    this.OnPropertyChanged("KCID");
                }
            }
        }
        [RemObjects.DataAbstract.Linq.FieldName("KKDATE")]
        [RemObjects.DataAbstract.Linq.DataType(RemObjects.DataAbstract.Schema.DataType.DateTime)]
        [RemObjects.DataAbstract.Linq.LogChanges()]
        public virtual System.Nullable<System.DateTime> KKDATE {
            get {
                return f____KKDATE;
            }
            set {
                if ((System.Collections.Generic.Comparer<System.Nullable<System.DateTime>>.Default.Compare(this.f____KKDATE, value) != 0)) {
                    this.OnPropertyChanging("KKDATE");
                    f____KKDATE = value;
                    this.OnPropertyChanged("KKDATE");
                }
            }
        }
        [RemObjects.DataAbstract.Linq.FieldName("KKNAME")]
        [RemObjects.DataAbstract.Linq.DataType(RemObjects.DataAbstract.Schema.DataType.WideString)]
        [RemObjects.DataAbstract.Linq.LogChanges()]
        public virtual string KKNAME {
            get {
                return f____KKNAME;
            }
            set {
                if ((System.Collections.Generic.Comparer<string>.Default.Compare(this.f____KKNAME, value) != 0)) {
                    this.OnPropertyChanging("KKNAME");
                    f____KKNAME = value;
                    this.OnPropertyChanged("KKNAME");
                }
            }
        }
        [RemObjects.DataAbstract.Linq.FieldName("KKNO")]
        [RemObjects.DataAbstract.Linq.DataType(RemObjects.DataAbstract.Schema.DataType.LargeInt)]
        [RemObjects.DataAbstract.Linq.LogChanges()]
        public virtual long KKNO {
            get {
                return f____KKNO;
            }
            set {
                if ((System.Collections.Generic.Comparer<long>.Default.Compare(this.f____KKNO, value) != 0)) {
                    this.OnPropertyChanging("KKNO");
                    f____KKNO = value;
                    this.OnPropertyChanged("KKNO");
                }
            }
        }
        [RemObjects.DataAbstract.Linq.FieldName("KSDATE")]
        [RemObjects.DataAbstract.Linq.DataType(RemObjects.DataAbstract.Schema.DataType.DateTime)]
        [RemObjects.DataAbstract.Linq.LogChanges()]
        public virtual System.Nullable<System.DateTime> KSDATE {
            get {
                return f____KSDATE;
            }
            set {
                if ((System.Collections.Generic.Comparer<System.Nullable<System.DateTime>>.Default.Compare(this.f____KSDATE, value) != 0)) {
                    this.OnPropertyChanging("KSDATE");
                    f____KSDATE = value;
                    this.OnPropertyChanged("KSDATE");
                }
            }
        }
        [RemObjects.DataAbstract.Linq.FieldName("RLSBNO")]
        [RemObjects.DataAbstract.Linq.DataType(RemObjects.DataAbstract.Schema.DataType.Decimal)]
        [RemObjects.DataAbstract.Linq.LogChanges()]
        public virtual System.Nullable<decimal> RLSBNO {
            get {
                return f____RLSBNO;
            }
            set {
                if ((System.Collections.Generic.Comparer<System.Nullable<decimal>>.Default.Compare(this.f____RLSBNO, value) != 0)) {
                    this.OnPropertyChanging("RLSBNO");
                    f____RLSBNO = value;
                    this.OnPropertyChanged("RLSBNO");
                }
            }
        }
        [RemObjects.DataAbstract.Linq.FieldName("XXRS")]
        [RemObjects.DataAbstract.Linq.DataType(RemObjects.DataAbstract.Schema.DataType.LargeInt)]
        [RemObjects.DataAbstract.Linq.LogChanges()]
        public virtual System.Nullable<long> XXRS {
            get {
                return f____XXRS;
            }
            set {
                if ((System.Collections.Generic.Comparer<System.Nullable<long>>.Default.Compare(this.f____XXRS, value) != 0)) {
                    this.OnPropertyChanging("XXRS");
                    f____XXRS = value;
                    this.OnPropertyChanged("XXRS");
                }
            }
        }
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
        object System.ICloneable.Clone() {
            JSANDKKVIEWRO v____new = new JSANDKKVIEWRO();
            v____new.f____JSID = this.f____JSID;
            v____new.f____JSNAME = this.f____JSNAME;
            v____new.f____JSSEX = this.f____JSSEX;
            v____new.f____XYID = this.f____XYID;
            v____new.f____JKDATE = this.f____JKDATE;
            v____new.f____KCID = this.f____KCID;
            v____new.f____KKDATE = this.f____KKDATE;
            v____new.f____KKNAME = this.f____KKNAME;
            v____new.f____KKNO = this.f____KKNO;
            v____new.f____KSDATE = this.f____KSDATE;
            v____new.f____RLSBNO = this.f____RLSBNO;
            v____new.f____XXRS = this.f____XXRS;
            return v____new;
        }
        public virtual void BeginUpdate() {
            this.m____OldValues = ((JSANDKKVIEWRO)(((System.ICloneable)(this)).Clone()));
        }
        public virtual void EndUpdate(RemObjects.DataAbstract.Linq.LinqDataAdapter dataAdapter) {
            dataAdapter.UpdateRow<JSANDKKVIEWRO>(this.m____OldValues, this);
            this.m____OldValues = null;
        }
        public virtual void CancelUpdate() {
            this.m____OldValues = null;
        }
        protected virtual void OnPropertyChanging(string parameterName) {
            if ((this.PropertyChanging != null)) {
                this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(parameterName));
            }
        }
        protected virtual void OnPropertyChanged(string parameterName) {
            if (((this.PropertyChanged != null) 
                        && (this.m____OldValues == null))) {
                this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(parameterName));
            }
        }
    }
    [RemObjects.DataAbstract.Linq.TableName("KKTABLE_05_VIEWRO")]
    public partial class KKTABLE_05_VIEWRO : System.ICloneable, System.ComponentModel.INotifyPropertyChanged, System.ComponentModel.INotifyPropertyChanging {
        protected KKTABLE_05_VIEWRO m____OldValues;
        private long f____KKNO;
        private string f____KKNAME;
        private System.Nullable<long> f____KCID;
        private string f____KCNAME;
        private System.Nullable<System.DateTime> f____KKDATE;
        private System.Nullable<System.DateTime> f____JKDATE;
        private System.Nullable<System.DateTime> f____KSDATE;
        private System.Nullable<long> f____XXRS;
        private System.Nullable<long> f____XYID;
        private string f____XYNAME;
        private System.Nullable<long> f____JSID;
        private string f____JSNAME;
        private System.Nullable<decimal> f____RLSBNO;
        [RemObjects.DataAbstract.Linq.FieldName("KKNO")]
        [RemObjects.DataAbstract.Linq.DataType(RemObjects.DataAbstract.Schema.DataType.LargeInt)]
        [RemObjects.DataAbstract.Linq.PrimaryKey()]
        [RemObjects.DataAbstract.Linq.LogChanges()]
        public virtual long KKNO {
            get {
                return f____KKNO;
            }
            set {
                if ((System.Collections.Generic.Comparer<long>.Default.Compare(this.f____KKNO, value) != 0)) {
                    this.OnPropertyChanging("KKNO");
                    f____KKNO = value;
                    this.OnPropertyChanged("KKNO");
                }
            }
        }
        [RemObjects.DataAbstract.Linq.FieldName("KKNAME")]
        [RemObjects.DataAbstract.Linq.DataType(RemObjects.DataAbstract.Schema.DataType.WideString)]
        [RemObjects.DataAbstract.Linq.LogChanges()]
        public virtual string KKNAME {
            get {
                return f____KKNAME;
            }
            set {
                if ((System.Collections.Generic.Comparer<string>.Default.Compare(this.f____KKNAME, value) != 0)) {
                    this.OnPropertyChanging("KKNAME");
                    f____KKNAME = value;
                    this.OnPropertyChanged("KKNAME");
                }
            }
        }
        [RemObjects.DataAbstract.Linq.FieldName("KCID")]
        [RemObjects.DataAbstract.Linq.DataType(RemObjects.DataAbstract.Schema.DataType.LargeInt)]
        [RemObjects.DataAbstract.Linq.LogChanges()]
        public virtual System.Nullable<long> KCID {
            get {
                return f____KCID;
            }
            set {
                if ((System.Collections.Generic.Comparer<System.Nullable<long>>.Default.Compare(this.f____KCID, value) != 0)) {
                    this.OnPropertyChanging("KCID");
                    f____KCID = value;
                    this.OnPropertyChanged("KCID");
                }
            }
        }
        [RemObjects.DataAbstract.Linq.FieldName("KCNAME")]
        [RemObjects.DataAbstract.Linq.DataType(RemObjects.DataAbstract.Schema.DataType.WideString)]
        [RemObjects.DataAbstract.Linq.LogChanges()]
        public virtual string KCNAME {
            get {
                return f____KCNAME;
            }
            set {
                if ((System.Collections.Generic.Comparer<string>.Default.Compare(this.f____KCNAME, value) != 0)) {
                    this.OnPropertyChanging("KCNAME");
                    f____KCNAME = value;
                    this.OnPropertyChanged("KCNAME");
                }
            }
        }
        [RemObjects.DataAbstract.Linq.FieldName("KKDATE")]
        [RemObjects.DataAbstract.Linq.DataType(RemObjects.DataAbstract.Schema.DataType.DateTime)]
        [RemObjects.DataAbstract.Linq.LogChanges()]
        public virtual System.Nullable<System.DateTime> KKDATE {
            get {
                return f____KKDATE;
            }
            set {
                if ((System.Collections.Generic.Comparer<System.Nullable<System.DateTime>>.Default.Compare(this.f____KKDATE, value) != 0)) {
                    this.OnPropertyChanging("KKDATE");
                    f____KKDATE = value;
                    this.OnPropertyChanged("KKDATE");
                }
            }
        }
        [RemObjects.DataAbstract.Linq.FieldName("JKDATE")]
        [RemObjects.DataAbstract.Linq.DataType(RemObjects.DataAbstract.Schema.DataType.DateTime)]
        [RemObjects.DataAbstract.Linq.LogChanges()]
        public virtual System.Nullable<System.DateTime> JKDATE {
            get {
                return f____JKDATE;
            }
            set {
                if ((System.Collections.Generic.Comparer<System.Nullable<System.DateTime>>.Default.Compare(this.f____JKDATE, value) != 0)) {
                    this.OnPropertyChanging("JKDATE");
                    f____JKDATE = value;
                    this.OnPropertyChanged("JKDATE");
                }
            }
        }
        [RemObjects.DataAbstract.Linq.FieldName("KSDATE")]
        [RemObjects.DataAbstract.Linq.DataType(RemObjects.DataAbstract.Schema.DataType.DateTime)]
        [RemObjects.DataAbstract.Linq.LogChanges()]
        public virtual System.Nullable<System.DateTime> KSDATE {
            get {
                return f____KSDATE;
            }
            set {
                if ((System.Collections.Generic.Comparer<System.Nullable<System.DateTime>>.Default.Compare(this.f____KSDATE, value) != 0)) {
                    this.OnPropertyChanging("KSDATE");
                    f____KSDATE = value;
                    this.OnPropertyChanged("KSDATE");
                }
            }
        }
        [RemObjects.DataAbstract.Linq.FieldName("XXRS")]
        [RemObjects.DataAbstract.Linq.DataType(RemObjects.DataAbstract.Schema.DataType.LargeInt)]
        [RemObjects.DataAbstract.Linq.LogChanges()]
        public virtual System.Nullable<long> XXRS {
            get {
                return f____XXRS;
            }
            set {
                if ((System.Collections.Generic.Comparer<System.Nullable<long>>.Default.Compare(this.f____XXRS, value) != 0)) {
                    this.OnPropertyChanging("XXRS");
                    f____XXRS = value;
                    this.OnPropertyChanged("XXRS");
                }
            }
        }
        [RemObjects.DataAbstract.Linq.FieldName("XYID")]
        [RemObjects.DataAbstract.Linq.DataType(RemObjects.DataAbstract.Schema.DataType.LargeInt)]
        [RemObjects.DataAbstract.Linq.LogChanges()]
        public virtual System.Nullable<long> XYID {
            get {
                return f____XYID;
            }
            set {
                if ((System.Collections.Generic.Comparer<System.Nullable<long>>.Default.Compare(this.f____XYID, value) != 0)) {
                    this.OnPropertyChanging("XYID");
                    f____XYID = value;
                    this.OnPropertyChanged("XYID");
                }
            }
        }
        [RemObjects.DataAbstract.Linq.FieldName("XYNAME")]
        [RemObjects.DataAbstract.Linq.DataType(RemObjects.DataAbstract.Schema.DataType.WideString)]
        [RemObjects.DataAbstract.Linq.LogChanges()]
        public virtual string XYNAME {
            get {
                return f____XYNAME;
            }
            set {
                f____XYNAME = value;
            }
        }
        [RemObjects.DataAbstract.Linq.FieldName("JSID")]
        [RemObjects.DataAbstract.Linq.DataType(RemObjects.DataAbstract.Schema.DataType.LargeInt)]
        [RemObjects.DataAbstract.Linq.LogChanges()]
        public virtual System.Nullable<long> JSID {
            get {
                return f____JSID;
            }
            set {
                if ((System.Collections.Generic.Comparer<System.Nullable<long>>.Default.Compare(this.f____JSID, value) != 0)) {
                    this.OnPropertyChanging("JSID");
                    f____JSID = value;
                    this.OnPropertyChanged("JSID");
                }
            }
        }
        [RemObjects.DataAbstract.Linq.FieldName("JSNAME")]
        [RemObjects.DataAbstract.Linq.DataType(RemObjects.DataAbstract.Schema.DataType.WideString)]
        [RemObjects.DataAbstract.Linq.LogChanges()]
        public virtual string JSNAME {
            get {
                return f____JSNAME;
            }
            set {
                f____JSNAME = value;
            }
        }
        [RemObjects.DataAbstract.Linq.FieldName("RLSBNO")]
        [RemObjects.DataAbstract.Linq.DataType(RemObjects.DataAbstract.Schema.DataType.Decimal)]
        [RemObjects.DataAbstract.Linq.LogChanges()]
        public virtual System.Nullable<decimal> RLSBNO {
            get {
                return f____RLSBNO;
            }
            set {
                if ((System.Collections.Generic.Comparer<System.Nullable<decimal>>.Default.Compare(this.f____RLSBNO, value) != 0)) {
                    this.OnPropertyChanging("RLSBNO");
                    f____RLSBNO = value;
                    this.OnPropertyChanged("RLSBNO");
                }
            }
        }
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
        object System.ICloneable.Clone() {
            KKTABLE_05_VIEWRO v____new = new KKTABLE_05_VIEWRO();
            v____new.f____KKNO = this.f____KKNO;
            v____new.f____KKNAME = this.f____KKNAME;
            v____new.f____KCID = this.f____KCID;
            v____new.f____KCNAME = this.f____KCNAME;
            v____new.f____KKDATE = this.f____KKDATE;
            v____new.f____JKDATE = this.f____JKDATE;
            v____new.f____KSDATE = this.f____KSDATE;
            v____new.f____XXRS = this.f____XXRS;
            v____new.f____XYID = this.f____XYID;
            v____new.f____XYNAME = this.f____XYNAME;
            v____new.f____JSID = this.f____JSID;
            v____new.f____JSNAME = this.f____JSNAME;
            v____new.f____RLSBNO = this.f____RLSBNO;
            return v____new;
        }
        public virtual void BeginUpdate() {
            this.m____OldValues = ((KKTABLE_05_VIEWRO)(((System.ICloneable)(this)).Clone()));
        }
        public virtual void EndUpdate(RemObjects.DataAbstract.Linq.LinqDataAdapter dataAdapter) {
            dataAdapter.UpdateRow<KKTABLE_05_VIEWRO>(this.m____OldValues, this);
            this.m____OldValues = null;
        }
        public virtual void CancelUpdate() {
            this.m____OldValues = null;
        }
        protected virtual void OnPropertyChanging(string parameterName) {
            if ((this.PropertyChanging != null)) {
                this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(parameterName));
            }
        }
        protected virtual void OnPropertyChanged(string parameterName) {
            if (((this.PropertyChanged != null) 
                        && (this.m____OldValues == null))) {
                this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(parameterName));
            }
        }
    }
    [RemObjects.DataAbstract.Linq.TableName("XKTABLE_VIEWRO")]
    public partial class XKTABLE_VIEWRO : System.ICloneable, System.ComponentModel.INotifyPropertyChanged, System.ComponentModel.INotifyPropertyChanging {
        protected XKTABLE_VIEWRO m____OldValues;
        private System.Nullable<long> f____KKNO;
        private string f____XSID;
        private System.Nullable<System.DateTime> f____JKDATE;
        private System.Nullable<long> f____JSID;
        private System.Nullable<long> f____KCID;
        private System.Nullable<System.DateTime> f____KKDATE;
        private string f____KKNAME;
        private System.Nullable<System.DateTime> f____KSDATE;
        private System.Nullable<decimal> f____RLSBNO;
        private System.Nullable<long> f____XXRS;
        private System.Nullable<long> f____XYID;
        private string f____KCNAME;
        private System.Nullable<short> f____KHLX;
        private System.Nullable<decimal> f____KS;
        private System.Nullable<long> f____BJID;
        private string f____XSNAME;
        private string f____XSSEX;
        private byte[] f____XSZP;
        private string f____ZW1;
        private string f____ZW2;
        private byte[] f____VOICE;
        private string f____RLSBGROUPNAME;
        [RemObjects.DataAbstract.Linq.FieldName("KKNO")]
        [RemObjects.DataAbstract.Linq.DataType(RemObjects.DataAbstract.Schema.DataType.LargeInt)]
        [RemObjects.DataAbstract.Linq.LogChanges()]
        public virtual System.Nullable<long> KKNO {
            get {
                return f____KKNO;
            }
            set {
                if ((System.Collections.Generic.Comparer<System.Nullable<long>>.Default.Compare(this.f____KKNO, value) != 0)) {
                    this.OnPropertyChanging("KKNO");
                    f____KKNO = value;
                    this.OnPropertyChanged("KKNO");
                }
            }
        }
        [RemObjects.DataAbstract.Linq.FieldName("XSID")]
        [RemObjects.DataAbstract.Linq.DataType(RemObjects.DataAbstract.Schema.DataType.WideString)]
        [RemObjects.DataAbstract.Linq.LogChanges()]
        public virtual string XSID {
            get {
                return f____XSID;
            }
            set {
                if ((System.Collections.Generic.Comparer<string>.Default.Compare(this.f____XSID, value) != 0)) {
                    this.OnPropertyChanging("XSID");
                    f____XSID = value;
                    this.OnPropertyChanged("XSID");
                }
            }
        }
        [RemObjects.DataAbstract.Linq.FieldName("JKDATE")]
        [RemObjects.DataAbstract.Linq.DataType(RemObjects.DataAbstract.Schema.DataType.DateTime)]
        [RemObjects.DataAbstract.Linq.LogChanges()]
        public virtual System.Nullable<System.DateTime> JKDATE {
            get {
                return f____JKDATE;
            }
            set {
                if ((System.Collections.Generic.Comparer<System.Nullable<System.DateTime>>.Default.Compare(this.f____JKDATE, value) != 0)) {
                    this.OnPropertyChanging("JKDATE");
                    f____JKDATE = value;
                    this.OnPropertyChanged("JKDATE");
                }
            }
        }
        [RemObjects.DataAbstract.Linq.FieldName("JSID")]
        [RemObjects.DataAbstract.Linq.DataType(RemObjects.DataAbstract.Schema.DataType.LargeInt)]
        [RemObjects.DataAbstract.Linq.LogChanges()]
        public virtual System.Nullable<long> JSID {
            get {
                return f____JSID;
            }
            set {
                if ((System.Collections.Generic.Comparer<System.Nullable<long>>.Default.Compare(this.f____JSID, value) != 0)) {
                    this.OnPropertyChanging("JSID");
                    f____JSID = value;
                    this.OnPropertyChanged("JSID");
                }
            }
        }
        [RemObjects.DataAbstract.Linq.FieldName("KCID")]
        [RemObjects.DataAbstract.Linq.DataType(RemObjects.DataAbstract.Schema.DataType.LargeInt)]
        [RemObjects.DataAbstract.Linq.LogChanges()]
        public virtual System.Nullable<long> KCID {
            get {
                return f____KCID;
            }
            set {
                if ((System.Collections.Generic.Comparer<System.Nullable<long>>.Default.Compare(this.f____KCID, value) != 0)) {
                    this.OnPropertyChanging("KCID");
                    f____KCID = value;
                    this.OnPropertyChanged("KCID");
                }
            }
        }
        [RemObjects.DataAbstract.Linq.FieldName("KKDATE")]
        [RemObjects.DataAbstract.Linq.DataType(RemObjects.DataAbstract.Schema.DataType.DateTime)]
        [RemObjects.DataAbstract.Linq.LogChanges()]
        public virtual System.Nullable<System.DateTime> KKDATE {
            get {
                return f____KKDATE;
            }
            set {
                if ((System.Collections.Generic.Comparer<System.Nullable<System.DateTime>>.Default.Compare(this.f____KKDATE, value) != 0)) {
                    this.OnPropertyChanging("KKDATE");
                    f____KKDATE = value;
                    this.OnPropertyChanged("KKDATE");
                }
            }
        }
        [RemObjects.DataAbstract.Linq.FieldName("KKNAME")]
        [RemObjects.DataAbstract.Linq.DataType(RemObjects.DataAbstract.Schema.DataType.WideString)]
        [RemObjects.DataAbstract.Linq.LogChanges()]
        public virtual string KKNAME {
            get {
                return f____KKNAME;
            }
            set {
                if ((System.Collections.Generic.Comparer<string>.Default.Compare(this.f____KKNAME, value) != 0)) {
                    this.OnPropertyChanging("KKNAME");
                    f____KKNAME = value;
                    this.OnPropertyChanged("KKNAME");
                }
            }
        }
        [RemObjects.DataAbstract.Linq.FieldName("KSDATE")]
        [RemObjects.DataAbstract.Linq.DataType(RemObjects.DataAbstract.Schema.DataType.DateTime)]
        [RemObjects.DataAbstract.Linq.LogChanges()]
        public virtual System.Nullable<System.DateTime> KSDATE {
            get {
                return f____KSDATE;
            }
            set {
                if ((System.Collections.Generic.Comparer<System.Nullable<System.DateTime>>.Default.Compare(this.f____KSDATE, value) != 0)) {
                    this.OnPropertyChanging("KSDATE");
                    f____KSDATE = value;
                    this.OnPropertyChanged("KSDATE");
                }
            }
        }
        [RemObjects.DataAbstract.Linq.FieldName("RLSBNO")]
        [RemObjects.DataAbstract.Linq.DataType(RemObjects.DataAbstract.Schema.DataType.Decimal)]
        [RemObjects.DataAbstract.Linq.LogChanges()]
        public virtual System.Nullable<decimal> RLSBNO {
            get {
                return f____RLSBNO;
            }
            set {
                if ((System.Collections.Generic.Comparer<System.Nullable<decimal>>.Default.Compare(this.f____RLSBNO, value) != 0)) {
                    this.OnPropertyChanging("RLSBNO");
                    f____RLSBNO = value;
                    this.OnPropertyChanged("RLSBNO");
                }
            }
        }
        [RemObjects.DataAbstract.Linq.FieldName("XXRS")]
        [RemObjects.DataAbstract.Linq.DataType(RemObjects.DataAbstract.Schema.DataType.LargeInt)]
        [RemObjects.DataAbstract.Linq.LogChanges()]
        public virtual System.Nullable<long> XXRS {
            get {
                return f____XXRS;
            }
            set {
                if ((System.Collections.Generic.Comparer<System.Nullable<long>>.Default.Compare(this.f____XXRS, value) != 0)) {
                    this.OnPropertyChanging("XXRS");
                    f____XXRS = value;
                    this.OnPropertyChanged("XXRS");
                }
            }
        }
        [RemObjects.DataAbstract.Linq.FieldName("XYID")]
        [RemObjects.DataAbstract.Linq.DataType(RemObjects.DataAbstract.Schema.DataType.LargeInt)]
        [RemObjects.DataAbstract.Linq.LogChanges()]
        public virtual System.Nullable<long> XYID {
            get {
                return f____XYID;
            }
            set {
                if ((System.Collections.Generic.Comparer<System.Nullable<long>>.Default.Compare(this.f____XYID, value) != 0)) {
                    this.OnPropertyChanging("XYID");
                    f____XYID = value;
                    this.OnPropertyChanged("XYID");
                }
            }
        }
        [RemObjects.DataAbstract.Linq.FieldName("KCNAME")]
        [RemObjects.DataAbstract.Linq.DataType(RemObjects.DataAbstract.Schema.DataType.WideString)]
        [RemObjects.DataAbstract.Linq.LogChanges()]
        public virtual string KCNAME {
            get {
                return f____KCNAME;
            }
            set {
                if ((System.Collections.Generic.Comparer<string>.Default.Compare(this.f____KCNAME, value) != 0)) {
                    this.OnPropertyChanging("KCNAME");
                    f____KCNAME = value;
                    this.OnPropertyChanged("KCNAME");
                }
            }
        }
        [RemObjects.DataAbstract.Linq.FieldName("KHLX")]
        [RemObjects.DataAbstract.Linq.DataType(RemObjects.DataAbstract.Schema.DataType.SmallInt)]
        [RemObjects.DataAbstract.Linq.LogChanges()]
        public virtual System.Nullable<short> KHLX {
            get {
                return f____KHLX;
            }
            set {
                if ((System.Collections.Generic.Comparer<System.Nullable<short>>.Default.Compare(this.f____KHLX, value) != 0)) {
                    this.OnPropertyChanging("KHLX");
                    f____KHLX = value;
                    this.OnPropertyChanged("KHLX");
                }
            }
        }
        [RemObjects.DataAbstract.Linq.FieldName("KS")]
        [RemObjects.DataAbstract.Linq.DataType(RemObjects.DataAbstract.Schema.DataType.Decimal)]
        [RemObjects.DataAbstract.Linq.LogChanges()]
        public virtual System.Nullable<decimal> KS {
            get {
                return f____KS;
            }
            set {
                if ((System.Collections.Generic.Comparer<System.Nullable<decimal>>.Default.Compare(this.f____KS, value) != 0)) {
                    this.OnPropertyChanging("KS");
                    f____KS = value;
                    this.OnPropertyChanged("KS");
                }
            }
        }
        [RemObjects.DataAbstract.Linq.FieldName("BJID")]
        [RemObjects.DataAbstract.Linq.DataType(RemObjects.DataAbstract.Schema.DataType.LargeInt)]
        [RemObjects.DataAbstract.Linq.LogChanges()]
        public virtual System.Nullable<long> BJID {
            get {
                return f____BJID;
            }
            set {
                if ((System.Collections.Generic.Comparer<System.Nullable<long>>.Default.Compare(this.f____BJID, value) != 0)) {
                    this.OnPropertyChanging("BJID");
                    f____BJID = value;
                    this.OnPropertyChanged("BJID");
                }
            }
        }
        [RemObjects.DataAbstract.Linq.FieldName("XSNAME")]
        [RemObjects.DataAbstract.Linq.DataType(RemObjects.DataAbstract.Schema.DataType.WideString)]
        [RemObjects.DataAbstract.Linq.LogChanges()]
        public virtual string XSNAME {
            get {
                return f____XSNAME;
            }
            set {
                if ((System.Collections.Generic.Comparer<string>.Default.Compare(this.f____XSNAME, value) != 0)) {
                    this.OnPropertyChanging("XSNAME");
                    f____XSNAME = value;
                    this.OnPropertyChanged("XSNAME");
                }
            }
        }
        [RemObjects.DataAbstract.Linq.FieldName("XSSEX")]
        [RemObjects.DataAbstract.Linq.DataType(RemObjects.DataAbstract.Schema.DataType.WideString)]
        [RemObjects.DataAbstract.Linq.LogChanges()]
        public virtual string XSSEX {
            get {
                return f____XSSEX;
            }
            set {
                if ((System.Collections.Generic.Comparer<string>.Default.Compare(this.f____XSSEX, value) != 0)) {
                    this.OnPropertyChanging("XSSEX");
                    f____XSSEX = value;
                    this.OnPropertyChanged("XSSEX");
                }
            }
        }
        [RemObjects.DataAbstract.Linq.FieldName("XSZP")]
        [RemObjects.DataAbstract.Linq.DataType(RemObjects.DataAbstract.Schema.DataType.Blob)]
        [RemObjects.DataAbstract.Linq.LogChanges()]
        public virtual byte[] XSZP {
            get {
                return f____XSZP;
            }
            set {
                if ((RemObjects.DataAbstract.Linq.LinqDataAdapter.CompareBytes(this.f____XSZP, value) != true)) {
                    this.OnPropertyChanging("XSZP");
                    f____XSZP = value;
                    this.OnPropertyChanged("XSZP");
                }
            }
        }
        [RemObjects.DataAbstract.Linq.FieldName("ZW1")]
        [RemObjects.DataAbstract.Linq.DataType(RemObjects.DataAbstract.Schema.DataType.WideString)]
        [RemObjects.DataAbstract.Linq.LogChanges()]
        public virtual string ZW1 {
            get {
                return f____ZW1;
            }
            set {
                if ((System.Collections.Generic.Comparer<string>.Default.Compare(this.f____ZW1, value) != 0)) {
                    this.OnPropertyChanging("ZW1");
                    f____ZW1 = value;
                    this.OnPropertyChanged("ZW1");
                }
            }
        }
        [RemObjects.DataAbstract.Linq.FieldName("ZW2")]
        [RemObjects.DataAbstract.Linq.DataType(RemObjects.DataAbstract.Schema.DataType.WideString)]
        [RemObjects.DataAbstract.Linq.LogChanges()]
        public virtual string ZW2 {
            get {
                return f____ZW2;
            }
            set {
                if ((System.Collections.Generic.Comparer<string>.Default.Compare(this.f____ZW2, value) != 0)) {
                    this.OnPropertyChanging("ZW2");
                    f____ZW2 = value;
                    this.OnPropertyChanged("ZW2");
                }
            }
        }
        [RemObjects.DataAbstract.Linq.FieldName("VOICE")]
        [RemObjects.DataAbstract.Linq.DataType(RemObjects.DataAbstract.Schema.DataType.Blob)]
        [RemObjects.DataAbstract.Linq.LogChanges()]
        public virtual byte[] VOICE {
            get {
                return f____VOICE;
            }
            set {
                if ((RemObjects.DataAbstract.Linq.LinqDataAdapter.CompareBytes(this.f____VOICE, value) != true)) {
                    this.OnPropertyChanging("VOICE");
                    f____VOICE = value;
                    this.OnPropertyChanged("VOICE");
                }
            }
        }
        [RemObjects.DataAbstract.Linq.FieldName("RLSBGROUPNAME")]
        [RemObjects.DataAbstract.Linq.DataType(RemObjects.DataAbstract.Schema.DataType.WideString)]
        [RemObjects.DataAbstract.Linq.LogChanges()]
        public virtual string RLSBGROUPNAME {
            get {
                return f____RLSBGROUPNAME;
            }
            set {
                if ((System.Collections.Generic.Comparer<string>.Default.Compare(this.f____RLSBGROUPNAME, value) != 0)) {
                    this.OnPropertyChanging("RLSBGROUPNAME");
                    f____RLSBGROUPNAME = value;
                    this.OnPropertyChanged("RLSBGROUPNAME");
                }
            }
        }
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
        object System.ICloneable.Clone() {
            XKTABLE_VIEWRO v____new = new XKTABLE_VIEWRO();
            v____new.f____KKNO = this.f____KKNO;
            v____new.f____XSID = this.f____XSID;
            v____new.f____JKDATE = this.f____JKDATE;
            v____new.f____JSID = this.f____JSID;
            v____new.f____KCID = this.f____KCID;
            v____new.f____KKDATE = this.f____KKDATE;
            v____new.f____KKNAME = this.f____KKNAME;
            v____new.f____KSDATE = this.f____KSDATE;
            v____new.f____RLSBNO = this.f____RLSBNO;
            v____new.f____XXRS = this.f____XXRS;
            v____new.f____XYID = this.f____XYID;
            v____new.f____KCNAME = this.f____KCNAME;
            v____new.f____KHLX = this.f____KHLX;
            v____new.f____KS = this.f____KS;
            v____new.f____BJID = this.f____BJID;
            v____new.f____XSNAME = this.f____XSNAME;
            v____new.f____XSSEX = this.f____XSSEX;
            v____new.f____XSZP = this.f____XSZP;
            v____new.f____ZW1 = this.f____ZW1;
            v____new.f____ZW2 = this.f____ZW2;
            v____new.f____VOICE = this.f____VOICE;
            v____new.f____RLSBGROUPNAME = this.f____RLSBGROUPNAME;
            return v____new;
        }
        public virtual void BeginUpdate() {
            this.m____OldValues = ((XKTABLE_VIEWRO)(((System.ICloneable)(this)).Clone()));
        }
        public virtual void EndUpdate(RemObjects.DataAbstract.Linq.LinqDataAdapter dataAdapter) {
            dataAdapter.UpdateRow<XKTABLE_VIEWRO>(this.m____OldValues, this);
            this.m____OldValues = null;
        }
        public virtual void CancelUpdate() {
            this.m____OldValues = null;
        }
        protected virtual void OnPropertyChanging(string parameterName) {
            if ((this.PropertyChanging != null)) {
                this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(parameterName));
            }
        }
        protected virtual void OnPropertyChanged(string parameterName) {
            if (((this.PropertyChanged != null) 
                        && (this.m____OldValues == null))) {
                this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(parameterName));
            }
        }
    }
    [RemObjects.DataAbstract.Linq.TableName("XYTABLE_02RO")]
    public partial class XYTABLE_02RO : System.ICloneable, System.ComponentModel.INotifyPropertyChanged, System.ComponentModel.INotifyPropertyChanging {
        protected XYTABLE_02RO m____OldValues;
        private long f____XYID;
        private string f____XYNAME;
        [RemObjects.DataAbstract.Linq.FieldName("XYID")]
        [RemObjects.DataAbstract.Linq.DataType(RemObjects.DataAbstract.Schema.DataType.LargeInt)]
        [RemObjects.DataAbstract.Linq.PrimaryKey()]
        [RemObjects.DataAbstract.Linq.LogChanges()]
        public virtual long XYID {
            get {
                return f____XYID;
            }
            set {
                if ((System.Collections.Generic.Comparer<long>.Default.Compare(this.f____XYID, value) != 0)) {
                    this.OnPropertyChanging("XYID");
                    f____XYID = value;
                    this.OnPropertyChanged("XYID");
                }
            }
        }
        [RemObjects.DataAbstract.Linq.FieldName("XYNAME")]
        [RemObjects.DataAbstract.Linq.DataType(RemObjects.DataAbstract.Schema.DataType.WideString)]
        [RemObjects.DataAbstract.Linq.LogChanges()]
        public virtual string XYNAME {
            get {
                return f____XYNAME;
            }
            set {
                if ((System.Collections.Generic.Comparer<string>.Default.Compare(this.f____XYNAME, value) != 0)) {
                    this.OnPropertyChanging("XYNAME");
                    f____XYNAME = value;
                    this.OnPropertyChanged("XYNAME");
                }
            }
        }
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
        object System.ICloneable.Clone() {
            XYTABLE_02RO v____new = new XYTABLE_02RO();
            v____new.f____XYID = this.f____XYID;
            v____new.f____XYNAME = this.f____XYNAME;
            return v____new;
        }
        public virtual void BeginUpdate() {
            this.m____OldValues = ((XYTABLE_02RO)(((System.ICloneable)(this)).Clone()));
        }
        public virtual void EndUpdate(RemObjects.DataAbstract.Linq.LinqDataAdapter dataAdapter) {
            dataAdapter.UpdateRow<XYTABLE_02RO>(this.m____OldValues, this);
            this.m____OldValues = null;
        }
        public virtual void CancelUpdate() {
            this.m____OldValues = null;
        }
        protected virtual void OnPropertyChanging(string parameterName) {
            if ((this.PropertyChanging != null)) {
                this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(parameterName));
            }
        }
        protected virtual void OnPropertyChanged(string parameterName) {
            if (((this.PropertyChanged != null) 
                        && (this.m____OldValues == null))) {
                this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(parameterName));
            }
        }
    }
    [RemObjects.DataAbstract.Linq.TableName("JSTABLE_03_VIEW")]
    public partial class JSTABLE_03_VIEW : System.ICloneable, System.ComponentModel.INotifyPropertyChanged, System.ComponentModel.INotifyPropertyChanging {
        protected JSTABLE_03_VIEW m____OldValues;
        private long f____JSID;
        private string f____JSNAME;
        private string f____JSSEX;
        private System.Nullable<long> f____XYID;
        private string f____XYNAME;
        private string f____JSPASSWORD;
        private string f____ZW1;
        private string f____ZW2;
        private byte[] f____ZW1PIC;
        private byte[] f____ZW2PIC;
        [RemObjects.DataAbstract.Linq.FieldName("JSID")]
        [RemObjects.DataAbstract.Linq.DataType(RemObjects.DataAbstract.Schema.DataType.LargeInt)]
        [RemObjects.DataAbstract.Linq.PrimaryKey()]
        [RemObjects.DataAbstract.Linq.LogChanges()]
        public virtual long JSID {
            get {
                return f____JSID;
            }
            set {
                if ((System.Collections.Generic.Comparer<long>.Default.Compare(this.f____JSID, value) != 0)) {
                    this.OnPropertyChanging("JSID");
                    f____JSID = value;
                    this.OnPropertyChanged("JSID");
                }
            }
        }
        [RemObjects.DataAbstract.Linq.FieldName("JSNAME")]
        [RemObjects.DataAbstract.Linq.DataType(RemObjects.DataAbstract.Schema.DataType.WideString)]
        [RemObjects.DataAbstract.Linq.LogChanges()]
        public virtual string JSNAME {
            get {
                return f____JSNAME;
            }
            set {
                if ((System.Collections.Generic.Comparer<string>.Default.Compare(this.f____JSNAME, value) != 0)) {
                    this.OnPropertyChanging("JSNAME");
                    f____JSNAME = value;
                    this.OnPropertyChanged("JSNAME");
                }
            }
        }
        [RemObjects.DataAbstract.Linq.FieldName("JSSEX")]
        [RemObjects.DataAbstract.Linq.DataType(RemObjects.DataAbstract.Schema.DataType.WideString)]
        [RemObjects.DataAbstract.Linq.LogChanges()]
        public virtual string JSSEX {
            get {
                return f____JSSEX;
            }
            set {
                if ((System.Collections.Generic.Comparer<string>.Default.Compare(this.f____JSSEX, value) != 0)) {
                    this.OnPropertyChanging("JSSEX");
                    f____JSSEX = value;
                    this.OnPropertyChanged("JSSEX");
                }
            }
        }
        [RemObjects.DataAbstract.Linq.FieldName("XYID")]
        [RemObjects.DataAbstract.Linq.DataType(RemObjects.DataAbstract.Schema.DataType.LargeInt)]
        [RemObjects.DataAbstract.Linq.LogChanges()]
        public virtual System.Nullable<long> XYID {
            get {
                return f____XYID;
            }
            set {
                if ((System.Collections.Generic.Comparer<System.Nullable<long>>.Default.Compare(this.f____XYID, value) != 0)) {
                    this.OnPropertyChanging("XYID");
                    f____XYID = value;
                    this.OnPropertyChanged("XYID");
                }
            }
        }
        [RemObjects.DataAbstract.Linq.FieldName("XYNAME")]
        [RemObjects.DataAbstract.Linq.DataType(RemObjects.DataAbstract.Schema.DataType.WideString)]
        [RemObjects.DataAbstract.Linq.LogChanges()]
        public virtual string XYNAME {
            get {
                return f____XYNAME;
            }
            set {
                f____XYNAME = value;
            }
        }
        [RemObjects.DataAbstract.Linq.FieldName("JSPASSWORD")]
        [RemObjects.DataAbstract.Linq.DataType(RemObjects.DataAbstract.Schema.DataType.WideString)]
        [RemObjects.DataAbstract.Linq.LogChanges()]
        public virtual string JSPASSWORD {
            get {
                return f____JSPASSWORD;
            }
            set {
                if ((System.Collections.Generic.Comparer<string>.Default.Compare(this.f____JSPASSWORD, value) != 0)) {
                    this.OnPropertyChanging("JSPASSWORD");
                    f____JSPASSWORD = value;
                    this.OnPropertyChanged("JSPASSWORD");
                }
            }
        }
        [RemObjects.DataAbstract.Linq.FieldName("ZW1")]
        [RemObjects.DataAbstract.Linq.DataType(RemObjects.DataAbstract.Schema.DataType.WideString)]
        [RemObjects.DataAbstract.Linq.LogChanges()]
        public virtual string ZW1 {
            get {
                return f____ZW1;
            }
            set {
                if ((System.Collections.Generic.Comparer<string>.Default.Compare(this.f____ZW1, value) != 0)) {
                    this.OnPropertyChanging("ZW1");
                    f____ZW1 = value;
                    this.OnPropertyChanged("ZW1");
                }
            }
        }
        [RemObjects.DataAbstract.Linq.FieldName("ZW2")]
        [RemObjects.DataAbstract.Linq.DataType(RemObjects.DataAbstract.Schema.DataType.WideString)]
        [RemObjects.DataAbstract.Linq.LogChanges()]
        public virtual string ZW2 {
            get {
                return f____ZW2;
            }
            set {
                if ((System.Collections.Generic.Comparer<string>.Default.Compare(this.f____ZW2, value) != 0)) {
                    this.OnPropertyChanging("ZW2");
                    f____ZW2 = value;
                    this.OnPropertyChanged("ZW2");
                }
            }
        }
        [RemObjects.DataAbstract.Linq.FieldName("ZW1PIC")]
        [RemObjects.DataAbstract.Linq.DataType(RemObjects.DataAbstract.Schema.DataType.Blob)]
        [RemObjects.DataAbstract.Linq.LogChanges()]
        public virtual byte[] ZW1PIC {
            get {
                return f____ZW1PIC;
            }
            set {
                if ((RemObjects.DataAbstract.Linq.LinqDataAdapter.CompareBytes(this.f____ZW1PIC, value) != true)) {
                    this.OnPropertyChanging("ZW1PIC");
                    f____ZW1PIC = value;
                    this.OnPropertyChanged("ZW1PIC");
                }
            }
        }
        [RemObjects.DataAbstract.Linq.FieldName("ZW2PIC")]
        [RemObjects.DataAbstract.Linq.DataType(RemObjects.DataAbstract.Schema.DataType.Blob)]
        [RemObjects.DataAbstract.Linq.LogChanges()]
        public virtual byte[] ZW2PIC {
            get {
                return f____ZW2PIC;
            }
            set {
                if ((RemObjects.DataAbstract.Linq.LinqDataAdapter.CompareBytes(this.f____ZW2PIC, value) != true)) {
                    this.OnPropertyChanging("ZW2PIC");
                    f____ZW2PIC = value;
                    this.OnPropertyChanged("ZW2PIC");
                }
            }
        }
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
        object System.ICloneable.Clone() {
            JSTABLE_03_VIEW v____new = new JSTABLE_03_VIEW();
            v____new.f____JSID = this.f____JSID;
            v____new.f____JSNAME = this.f____JSNAME;
            v____new.f____JSSEX = this.f____JSSEX;
            v____new.f____XYID = this.f____XYID;
            v____new.f____XYNAME = this.f____XYNAME;
            v____new.f____JSPASSWORD = this.f____JSPASSWORD;
            v____new.f____ZW1 = this.f____ZW1;
            v____new.f____ZW2 = this.f____ZW2;
            v____new.f____ZW1PIC = this.f____ZW1PIC;
            v____new.f____ZW2PIC = this.f____ZW2PIC;
            return v____new;
        }
        public virtual void BeginUpdate() {
            this.m____OldValues = ((JSTABLE_03_VIEW)(((System.ICloneable)(this)).Clone()));
        }
        public virtual void EndUpdate(RemObjects.DataAbstract.Linq.LinqDataAdapter dataAdapter) {
            dataAdapter.UpdateRow<JSTABLE_03_VIEW>(this.m____OldValues, this);
            this.m____OldValues = null;
        }
        public virtual void CancelUpdate() {
            this.m____OldValues = null;
        }
        protected virtual void OnPropertyChanging(string parameterName) {
            if ((this.PropertyChanging != null)) {
                this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(parameterName));
            }
        }
        protected virtual void OnPropertyChanged(string parameterName) {
            if (((this.PropertyChanged != null) 
                        && (this.m____OldValues == null))) {
                this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(parameterName));
            }
        }
    }
    [RemObjects.DataAbstract.Linq.TableName("SKTABLE_07_VIEWRO")]
    public partial class SKTABLE_07_VIEWRO : System.ICloneable, System.ComponentModel.INotifyPropertyChanged, System.ComponentModel.INotifyPropertyChanging {
        protected SKTABLE_07_VIEWRO m____OldValues;
        private long f____SKNO;
        private System.Nullable<long> f____KKNO;
        private string f____KKNAME;
        private System.Nullable<System.DateTime> f____SKDATE;
        private System.Nullable<long> f____LSJS;
        private System.Nullable<short> f____DMFS;
        private System.Nullable<short> f____RZFS;
        private System.Nullable<short> f____CDRS;
        private System.Nullable<short> f____ZTRS;
        private System.Nullable<short> f____KKRS;
        private System.Nullable<short> f____ZCRS;
        private System.Nullable<System.DateTime> f____EDITDATE;
        private System.Nullable<long> f____EDITMANNO;
        private System.Nullable<System.DateTime> f____XKDATE;
        private System.Nullable<System.DateTime> f____YDSKDATE;
        private System.Nullable<System.DateTime> f____YDXKDATE;
        private string f____DMPASSWORD;
        private System.Nullable<short> f____SKZT;
        [RemObjects.DataAbstract.Linq.FieldName("SKNO")]
        [RemObjects.DataAbstract.Linq.DataType(RemObjects.DataAbstract.Schema.DataType.LargeInt)]
        [RemObjects.DataAbstract.Linq.PrimaryKey()]
        [RemObjects.DataAbstract.Linq.LogChanges()]
        public virtual long SKNO {
            get {
                return f____SKNO;
            }
            set {
                if ((System.Collections.Generic.Comparer<long>.Default.Compare(this.f____SKNO, value) != 0)) {
                    this.OnPropertyChanging("SKNO");
                    f____SKNO = value;
                    this.OnPropertyChanged("SKNO");
                }
            }
        }
        [RemObjects.DataAbstract.Linq.FieldName("KKNO")]
        [RemObjects.DataAbstract.Linq.DataType(RemObjects.DataAbstract.Schema.DataType.LargeInt)]
        [RemObjects.DataAbstract.Linq.LogChanges()]
        public virtual System.Nullable<long> KKNO {
            get {
                return f____KKNO;
            }
            set {
                if ((System.Collections.Generic.Comparer<System.Nullable<long>>.Default.Compare(this.f____KKNO, value) != 0)) {
                    this.OnPropertyChanging("KKNO");
                    f____KKNO = value;
                    this.OnPropertyChanged("KKNO");
                }
            }
        }
        [RemObjects.DataAbstract.Linq.FieldName("KKNAME")]
        [RemObjects.DataAbstract.Linq.DataType(RemObjects.DataAbstract.Schema.DataType.WideString)]
        [RemObjects.DataAbstract.Linq.LogChanges()]
        public virtual string KKNAME {
            get {
                return f____KKNAME;
            }
            set {
                f____KKNAME = value;
            }
        }
        [RemObjects.DataAbstract.Linq.FieldName("SKDATE")]
        [RemObjects.DataAbstract.Linq.DataType(RemObjects.DataAbstract.Schema.DataType.DateTime)]
        [RemObjects.DataAbstract.Linq.LogChanges()]
        public virtual System.Nullable<System.DateTime> SKDATE {
            get {
                return f____SKDATE;
            }
            set {
                if ((System.Collections.Generic.Comparer<System.Nullable<System.DateTime>>.Default.Compare(this.f____SKDATE, value) != 0)) {
                    this.OnPropertyChanging("SKDATE");
                    f____SKDATE = value;
                    this.OnPropertyChanged("SKDATE");
                }
            }
        }
        [RemObjects.DataAbstract.Linq.FieldName("LSJS")]
        [RemObjects.DataAbstract.Linq.DataType(RemObjects.DataAbstract.Schema.DataType.LargeInt)]
        [RemObjects.DataAbstract.Linq.LogChanges()]
        public virtual System.Nullable<long> LSJS {
            get {
                return f____LSJS;
            }
            set {
                if ((System.Collections.Generic.Comparer<System.Nullable<long>>.Default.Compare(this.f____LSJS, value) != 0)) {
                    this.OnPropertyChanging("LSJS");
                    f____LSJS = value;
                    this.OnPropertyChanged("LSJS");
                }
            }
        }
        [RemObjects.DataAbstract.Linq.FieldName("DMFS")]
        [RemObjects.DataAbstract.Linq.DataType(RemObjects.DataAbstract.Schema.DataType.SmallInt)]
        [RemObjects.DataAbstract.Linq.LogChanges()]
        public virtual System.Nullable<short> DMFS {
            get {
                return f____DMFS;
            }
            set {
                if ((System.Collections.Generic.Comparer<System.Nullable<short>>.Default.Compare(this.f____DMFS, value) != 0)) {
                    this.OnPropertyChanging("DMFS");
                    f____DMFS = value;
                    this.OnPropertyChanged("DMFS");
                }
            }
        }
        [RemObjects.DataAbstract.Linq.FieldName("RZFS")]
        [RemObjects.DataAbstract.Linq.DataType(RemObjects.DataAbstract.Schema.DataType.SmallInt)]
        [RemObjects.DataAbstract.Linq.LogChanges()]
        public virtual System.Nullable<short> RZFS {
            get {
                return f____RZFS;
            }
            set {
                if ((System.Collections.Generic.Comparer<System.Nullable<short>>.Default.Compare(this.f____RZFS, value) != 0)) {
                    this.OnPropertyChanging("RZFS");
                    f____RZFS = value;
                    this.OnPropertyChanged("RZFS");
                }
            }
        }
        [RemObjects.DataAbstract.Linq.FieldName("CDRS")]
        [RemObjects.DataAbstract.Linq.DataType(RemObjects.DataAbstract.Schema.DataType.SmallInt)]
        [RemObjects.DataAbstract.Linq.LogChanges()]
        public virtual System.Nullable<short> CDRS {
            get {
                return f____CDRS;
            }
            set {
                if ((System.Collections.Generic.Comparer<System.Nullable<short>>.Default.Compare(this.f____CDRS, value) != 0)) {
                    this.OnPropertyChanging("CDRS");
                    f____CDRS = value;
                    this.OnPropertyChanged("CDRS");
                }
            }
        }
        [RemObjects.DataAbstract.Linq.FieldName("ZTRS")]
        [RemObjects.DataAbstract.Linq.DataType(RemObjects.DataAbstract.Schema.DataType.SmallInt)]
        [RemObjects.DataAbstract.Linq.LogChanges()]
        public virtual System.Nullable<short> ZTRS {
            get {
                return f____ZTRS;
            }
            set {
                if ((System.Collections.Generic.Comparer<System.Nullable<short>>.Default.Compare(this.f____ZTRS, value) != 0)) {
                    this.OnPropertyChanging("ZTRS");
                    f____ZTRS = value;
                    this.OnPropertyChanged("ZTRS");
                }
            }
        }
        [RemObjects.DataAbstract.Linq.FieldName("KKRS")]
        [RemObjects.DataAbstract.Linq.DataType(RemObjects.DataAbstract.Schema.DataType.SmallInt)]
        [RemObjects.DataAbstract.Linq.LogChanges()]
        public virtual System.Nullable<short> KKRS {
            get {
                return f____KKRS;
            }
            set {
                if ((System.Collections.Generic.Comparer<System.Nullable<short>>.Default.Compare(this.f____KKRS, value) != 0)) {
                    this.OnPropertyChanging("KKRS");
                    f____KKRS = value;
                    this.OnPropertyChanged("KKRS");
                }
            }
        }
        [RemObjects.DataAbstract.Linq.FieldName("ZCRS")]
        [RemObjects.DataAbstract.Linq.DataType(RemObjects.DataAbstract.Schema.DataType.SmallInt)]
        [RemObjects.DataAbstract.Linq.LogChanges()]
        public virtual System.Nullable<short> ZCRS {
            get {
                return f____ZCRS;
            }
            set {
                if ((System.Collections.Generic.Comparer<System.Nullable<short>>.Default.Compare(this.f____ZCRS, value) != 0)) {
                    this.OnPropertyChanging("ZCRS");
                    f____ZCRS = value;
                    this.OnPropertyChanged("ZCRS");
                }
            }
        }
        [RemObjects.DataAbstract.Linq.FieldName("EDITDATE")]
        [RemObjects.DataAbstract.Linq.DataType(RemObjects.DataAbstract.Schema.DataType.DateTime)]
        [RemObjects.DataAbstract.Linq.LogChanges()]
        public virtual System.Nullable<System.DateTime> EDITDATE {
            get {
                return f____EDITDATE;
            }
            set {
                if ((System.Collections.Generic.Comparer<System.Nullable<System.DateTime>>.Default.Compare(this.f____EDITDATE, value) != 0)) {
                    this.OnPropertyChanging("EDITDATE");
                    f____EDITDATE = value;
                    this.OnPropertyChanged("EDITDATE");
                }
            }
        }
        [RemObjects.DataAbstract.Linq.FieldName("EDITMANNO")]
        [RemObjects.DataAbstract.Linq.DataType(RemObjects.DataAbstract.Schema.DataType.LargeInt)]
        [RemObjects.DataAbstract.Linq.LogChanges()]
        public virtual System.Nullable<long> EDITMANNO {
            get {
                return f____EDITMANNO;
            }
            set {
                if ((System.Collections.Generic.Comparer<System.Nullable<long>>.Default.Compare(this.f____EDITMANNO, value) != 0)) {
                    this.OnPropertyChanging("EDITMANNO");
                    f____EDITMANNO = value;
                    this.OnPropertyChanged("EDITMANNO");
                }
            }
        }
        [RemObjects.DataAbstract.Linq.FieldName("XKDATE")]
        [RemObjects.DataAbstract.Linq.DataType(RemObjects.DataAbstract.Schema.DataType.DateTime)]
        [RemObjects.DataAbstract.Linq.LogChanges()]
        public virtual System.Nullable<System.DateTime> XKDATE {
            get {
                return f____XKDATE;
            }
            set {
                if ((System.Collections.Generic.Comparer<System.Nullable<System.DateTime>>.Default.Compare(this.f____XKDATE, value) != 0)) {
                    this.OnPropertyChanging("XKDATE");
                    f____XKDATE = value;
                    this.OnPropertyChanged("XKDATE");
                }
            }
        }
        [RemObjects.DataAbstract.Linq.FieldName("YDSKDATE")]
        [RemObjects.DataAbstract.Linq.DataType(RemObjects.DataAbstract.Schema.DataType.DateTime)]
        [RemObjects.DataAbstract.Linq.LogChanges()]
        public virtual System.Nullable<System.DateTime> YDSKDATE {
            get {
                return f____YDSKDATE;
            }
            set {
                if ((System.Collections.Generic.Comparer<System.Nullable<System.DateTime>>.Default.Compare(this.f____YDSKDATE, value) != 0)) {
                    this.OnPropertyChanging("YDSKDATE");
                    f____YDSKDATE = value;
                    this.OnPropertyChanged("YDSKDATE");
                }
            }
        }
        [RemObjects.DataAbstract.Linq.FieldName("YDXKDATE")]
        [RemObjects.DataAbstract.Linq.DataType(RemObjects.DataAbstract.Schema.DataType.DateTime)]
        [RemObjects.DataAbstract.Linq.LogChanges()]
        public virtual System.Nullable<System.DateTime> YDXKDATE {
            get {
                return f____YDXKDATE;
            }
            set {
                if ((System.Collections.Generic.Comparer<System.Nullable<System.DateTime>>.Default.Compare(this.f____YDXKDATE, value) != 0)) {
                    this.OnPropertyChanging("YDXKDATE");
                    f____YDXKDATE = value;
                    this.OnPropertyChanged("YDXKDATE");
                }
            }
        }
        [RemObjects.DataAbstract.Linq.FieldName("DMPASSWORD")]
        [RemObjects.DataAbstract.Linq.DataType(RemObjects.DataAbstract.Schema.DataType.WideString)]
        [RemObjects.DataAbstract.Linq.LogChanges()]
        public virtual string DMPASSWORD {
            get {
                return f____DMPASSWORD;
            }
            set {
                if ((System.Collections.Generic.Comparer<string>.Default.Compare(this.f____DMPASSWORD, value) != 0)) {
                    this.OnPropertyChanging("DMPASSWORD");
                    f____DMPASSWORD = value;
                    this.OnPropertyChanged("DMPASSWORD");
                }
            }
        }
        [RemObjects.DataAbstract.Linq.FieldName("SKZT")]
        [RemObjects.DataAbstract.Linq.DataType(RemObjects.DataAbstract.Schema.DataType.SmallInt)]
        [RemObjects.DataAbstract.Linq.LogChanges()]
        public virtual System.Nullable<short> SKZT {
            get {
                return f____SKZT;
            }
            set {
                if ((System.Collections.Generic.Comparer<System.Nullable<short>>.Default.Compare(this.f____SKZT, value) != 0)) {
                    this.OnPropertyChanging("SKZT");
                    f____SKZT = value;
                    this.OnPropertyChanged("SKZT");
                }
            }
        }
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
        object System.ICloneable.Clone() {
            SKTABLE_07_VIEWRO v____new = new SKTABLE_07_VIEWRO();
            v____new.f____SKNO = this.f____SKNO;
            v____new.f____KKNO = this.f____KKNO;
            v____new.f____KKNAME = this.f____KKNAME;
            v____new.f____SKDATE = this.f____SKDATE;
            v____new.f____LSJS = this.f____LSJS;
            v____new.f____DMFS = this.f____DMFS;
            v____new.f____RZFS = this.f____RZFS;
            v____new.f____CDRS = this.f____CDRS;
            v____new.f____ZTRS = this.f____ZTRS;
            v____new.f____KKRS = this.f____KKRS;
            v____new.f____ZCRS = this.f____ZCRS;
            v____new.f____EDITDATE = this.f____EDITDATE;
            v____new.f____EDITMANNO = this.f____EDITMANNO;
            v____new.f____XKDATE = this.f____XKDATE;
            v____new.f____YDSKDATE = this.f____YDSKDATE;
            v____new.f____YDXKDATE = this.f____YDXKDATE;
            v____new.f____DMPASSWORD = this.f____DMPASSWORD;
            v____new.f____SKZT = this.f____SKZT;
            return v____new;
        }
        public virtual void BeginUpdate() {
            this.m____OldValues = ((SKTABLE_07_VIEWRO)(((System.ICloneable)(this)).Clone()));
        }
        public virtual void EndUpdate(RemObjects.DataAbstract.Linq.LinqDataAdapter dataAdapter) {
            dataAdapter.UpdateRow<SKTABLE_07_VIEWRO>(this.m____OldValues, this);
            this.m____OldValues = null;
        }
        public virtual void CancelUpdate() {
            this.m____OldValues = null;
        }
        protected virtual void OnPropertyChanging(string parameterName) {
            if ((this.PropertyChanging != null)) {
                this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(parameterName));
            }
        }
        protected virtual void OnPropertyChanged(string parameterName) {
            if (((this.PropertyChanged != null) 
                        && (this.m____OldValues == null))) {
                this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(parameterName));
            }
        }
    }
    public partial class DataContext {
        private System.Collections.Generic.IEnumerable<BJTABLE_09_VIEWRO> f____BJTABLE_09_VIEWRO;
        private System.Collections.Generic.IEnumerable<DMTABLE_08_NOPIC_VIEW> f____DMTABLE_08_NOPIC_VIEW;
        private System.Collections.Generic.IEnumerable<JSANDKKVIEWRO> f____JSANDKKVIEWRO;
        private System.Collections.Generic.IEnumerable<KKTABLE_05_VIEWRO> f____KKTABLE_05_VIEWRO;
        private System.Collections.Generic.IEnumerable<XKTABLE_VIEWRO> f____XKTABLE_VIEWRO;
        private System.Collections.Generic.IEnumerable<XYTABLE_02RO> f____XYTABLE_02RO;
        private System.Collections.Generic.IEnumerable<JSTABLE_03_VIEW> f____JSTABLE_03_VIEW;
        private System.Collections.Generic.IEnumerable<SKTABLE_07_VIEWRO> f____SKTABLE_07_VIEWRO;
        public DataContext() {
        }
        public virtual System.Collections.Generic.IEnumerable<BJTABLE_09_VIEWRO> BJTABLE_09_VIEWRO {
            get {
                return f____BJTABLE_09_VIEWRO;
            }
            set {
                f____BJTABLE_09_VIEWRO = value;
            }
        }
        public virtual System.Collections.Generic.IEnumerable<DMTABLE_08_NOPIC_VIEW> DMTABLE_08_NOPIC_VIEW {
            get {
                return f____DMTABLE_08_NOPIC_VIEW;
            }
            set {
                f____DMTABLE_08_NOPIC_VIEW = value;
            }
        }
        public virtual System.Collections.Generic.IEnumerable<JSANDKKVIEWRO> JSANDKKVIEWRO {
            get {
                return f____JSANDKKVIEWRO;
            }
            set {
                f____JSANDKKVIEWRO = value;
            }
        }
        public virtual System.Collections.Generic.IEnumerable<KKTABLE_05_VIEWRO> KKTABLE_05_VIEWRO {
            get {
                return f____KKTABLE_05_VIEWRO;
            }
            set {
                f____KKTABLE_05_VIEWRO = value;
            }
        }
        public virtual System.Collections.Generic.IEnumerable<XKTABLE_VIEWRO> XKTABLE_VIEWRO {
            get {
                return f____XKTABLE_VIEWRO;
            }
            set {
                f____XKTABLE_VIEWRO = value;
            }
        }
        public virtual System.Collections.Generic.IEnumerable<XYTABLE_02RO> XYTABLE_02RO {
            get {
                return f____XYTABLE_02RO;
            }
            set {
                f____XYTABLE_02RO = value;
            }
        }
        public virtual System.Collections.Generic.IEnumerable<JSTABLE_03_VIEW> JSTABLE_03_VIEW {
            get {
                return f____JSTABLE_03_VIEW;
            }
            set {
                f____JSTABLE_03_VIEW = value;
            }
        }
        public virtual System.Collections.Generic.IEnumerable<SKTABLE_07_VIEWRO> SKTABLE_07_VIEWRO {
            get {
                return f____SKTABLE_07_VIEWRO;
            }
            set {
                f____SKTABLE_07_VIEWRO = value;
            }
        }
    }
}
